# Generated by Django 5.1.7 on 2025-04-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookiing_date',
            new_name='journey_date',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='date',
        ),
    ]
