# Generated by Django 5.1.7 on 2025-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0002_rename_bookiing_date_booking_journey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
